<?php

class EvaluationTable extends BaseModel {
    public function tableName() {
        return '{{eval_table}}';
    }

    /**
     * 模型验证规则
     */
    public function rules() {
        return array(
//            array('eval_id', 'required', 'message' => '{attribute} 不能为空'),
//            array('dish', 'unique', 'message' => '已存在{attribute}!'),
//            array('nice', 'required', 'message' => '{attribute} 不能为空'),
            array('eval_id,dish,nice','safe'),
        );
    }

    /**
     * 模型关联规则
     */
    public function relations() {
        return array(
        );
    }

    /**
     * 属性标签
     */
    public function attributeLabels() {
        return array(
            'id' => 'ID',
            'dish'=>'菜品',
            'nice'=>'好坏',
            'r_id'=>'评价ID',
        );
    }
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public static function put_msg($pmsg)
    {
//        $this->isNewRecord = true;
//        $this->f_msg=$pmsg;
//        $this->save();
    }
    protected function afterFind()
    {

        parent::afterFind(); // TODO: Change the autogenerated stub

    }

    protected function beforeSave()
    {
        parent::beforeSave();

        return true;
    }

}

