<?php


class Restaurant extends BaseModel
{
    public $selectval = array(2);

    public function tableName()
    {
        return '{{rest}}';
    }

    /**
     * 模型验证规则
     */
    public function rules()
    {
        return array(
            array('r_name', 'required', 'message' => '{attribute} 不能为空'),
            array('r_price', 'required', 'message' => '{attribute} 不能为空'),
            array('r_price','numerical','min'=>'0'),
            array('r_service', 'required', 'message' => '{attribute} 不能为空'),
            array('r_service','numerical','min'=>'0','max'=>'5','message' => '{attribute} 范围需在1-5内'),
            array('r_address', 'required', 'message' => '{attribute} 不能为空'),
            array('r_rank', 'required', 'message' => '{attribute} 不能为空'),
            array('r_phone', 'required', 'message' => '{attribute} 不能为空'),
//            array('r_image', 'required', 'message' => '{attribute} 不能为空'),
            array('r_introduce', 'required', 'message' => '{attribute} 不能为空'),
            array('r_name,r_price,r_service,r_address,r_rank,r_phone,r_introduce,r_like','safe'),
        );
    }

    /**
     * 模型关联规则
     */
    public function relations()
    {
        return array();
    }

    /**
     * 属性标签
     */
    /*
                             isupload    ispass
                未上传            0          0
                上传中            0          1
                退回              1          0
                审核通过           1          1
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'r_name' => '名称',
            'r_address' => '地址',
            'r_price' => '人均价格',
            'r_service'=> '服务质量（1~5）',
            'r_rank'=> '地区排名',
            'r_phone'=> '联系方式',
            'r_image'=>'图片',
            'r_introduce'=>'介绍',
            'r_isupload'=>'是否已上传',
            'r_ispass'=>'是否已通过',
            'r_reason'=>'退回原因',
            'r_like'=>'是否收藏',
        );

    }


    /**
     * Returns the static model of the specified AR class.
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public static function put_msg($pmsg)
    {
//        $this->isNewRecord = true;
//        $this->f_msg=$pmsg;
//        $this->save();
    }

    public function getName() {
        $criteria = new CDbCriteria;
        $criteria->select='f_name';
        $criteria->addCondition("r_name = :r_name");
        if(!empty($f_order)) $criteria->order='id ASC';

        $result=$this->model()->findAll($criteria);
        return $result;
    }

    protected function afterFind()
    {

        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->r_image=addUploadPath($this->r_image);
    }
    protected function beforeSave()
    {
        parent::beforeSave();
        return true;
    }

}